[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "twitter-wednesday-bot"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [{name = "@baumannalexj"}]
requires-python = ">=3.9,<4.0"
dependencies = [
    "core @ file:core",
    "clients @ file:clients",
    "app-lambda-handler-isitwednesday-cron @ file:app_lambda_handler_isitwednesday_cron",
    "app-lambda-handler-social-listener @ file:app_lambda_handler_social_listener",
]

[project.optional-dependencies]
dev = ["pytest>=5.2"]

[project.urls]
repository = "https://github.com/baumannalexj/twitter-wednesday-bot"

[tool.pytest.ini_options]
python_files = ["test.py", "test_*.py", "*_test.py"]
testpaths = ["./**/tests"]

[tool.setuptools]
packages = []
