[project]
name = "twitter-wednesday-bot"
version = "0.1.1"
description = ""
readme = "README.md"
authors = [{name = "alexander baumann", email = "baumannalexj@gmail.com"}]
requires-python = ">=3.13"
dependencies = []

[project.urls]
repository = "https://github.com/baumannalexj/twitter-wednesday-bot"

[dependency-groups]
dev = ["pytest>=5.2"]

[tool.uv.workspace]
members = [
    "core",
    "clients",
    "app_isitwednesday_post",
    "app_isitwednesday_reply",
]

[tool.pytest.ini_options]
python_files = ["test.py", "test_*.py", "*_test.py"]
testpaths = ["**/tests"]
